import type { Ingredient } from '@/lib/calculator/types'

/** Mirrors the seed data in supabase/schema.sql, used when Supabase isn't configured yet
 *  so the calculator is still usable (read-only demo, no persistence) right after cloning. */
export const DEMO_INGREDIENTS: Ingredient[] = [
  { id: 'demo-strawberry', name: '草莓', category: 'fruit', waterPct: 87, sugarPct: 9, otherSolidsPct: 4, totalSolidsPct: 13, recommendedMinPct: 35, recommendedMaxPct: 60, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-peach', name: '桃子', category: 'fruit', waterPct: 83, sugarPct: 8, otherSolidsPct: 9, totalSolidsPct: 17, recommendedMinPct: 50, recommendedMaxPct: 60, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-mango', name: '芒果', category: 'fruit', waterPct: 82, sugarPct: 15, otherSolidsPct: 3, totalSolidsPct: 18, recommendedMinPct: 40, recommendedMaxPct: 60, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-banana', name: '香蕉', category: 'fruit', waterPct: 77, sugarPct: 15, otherSolidsPct: 8, totalSolidsPct: 23, recommendedMinPct: 50, recommendedMaxPct: 60, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-pineapple', name: '鳳梨', category: 'fruit', waterPct: 79, sugarPct: 12, otherSolidsPct: 9, totalSolidsPct: 21, recommendedMinPct: 45, recommendedMaxPct: 60, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-passionfruit', name: '百香果', category: 'fruit', waterPct: 82, sugarPct: 11, otherSolidsPct: 7, totalSolidsPct: 18, recommendedMinPct: 30, recommendedMaxPct: 45, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-raspberry', name: '覆盆子', category: 'fruit', waterPct: 83, sugarPct: 14, otherSolidsPct: 3, totalSolidsPct: 17, recommendedMinPct: 45, recommendedMaxPct: 55, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-blueberry', name: '藍莓', category: 'fruit', waterPct: 84, sugarPct: 12, otherSolidsPct: 4, totalSolidsPct: 16, recommendedMinPct: 45, recommendedMaxPct: 55, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-pomelo', name: '柚子', category: 'fruit', waterPct: 89, sugarPct: 8, otherSolidsPct: 3, totalSolidsPct: 11, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-lemon', name: '檸檬', category: 'fruit', waterPct: 90, sugarPct: 9, otherSolidsPct: 1, totalSolidsPct: 10, recommendedMinPct: 25, recommendedMaxPct: 35, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-orange', name: '柳橙', category: 'fruit', waterPct: 87, sugarPct: 10, otherSolidsPct: 3, totalSolidsPct: 13, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-mandarin', name: '橘子', category: 'fruit', waterPct: 84, sugarPct: 8, otherSolidsPct: 8, totalSolidsPct: 16, recommendedMinPct: 55, recommendedMaxPct: 60, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-kumquat', name: '小橘子', category: 'fruit', waterPct: 80, sugarPct: 12, otherSolidsPct: 8, totalSolidsPct: 20, recommendedMinPct: 45, recommendedMaxPct: 55, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-pear', name: '西洋梨', category: 'fruit', waterPct: 85, sugarPct: 9, otherSolidsPct: 6, totalSolidsPct: 15, recommendedMinPct: 50, recommendedMaxPct: 60, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-kiwi', name: '奇異果', category: 'fruit', waterPct: 88, sugarPct: 9, otherSolidsPct: 3, totalSolidsPct: 12, recommendedMinPct: 40, recommendedMaxPct: 60, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-grapefruit', name: '葡萄柚', category: 'fruit', waterPct: 87, sugarPct: 7, otherSolidsPct: 6, totalSolidsPct: 13, recommendedMinPct: 35, recommendedMaxPct: 50, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-cantaloupe', name: '哈密瓜', category: 'fruit', waterPct: 87, sugarPct: 8, otherSolidsPct: 5, totalSolidsPct: 13, recommendedMinPct: 40, recommendedMaxPct: 60, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-watermelon', name: '西瓜', category: 'fruit', waterPct: 89, sugarPct: 6, otherSolidsPct: 5, totalSolidsPct: 11, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-cherry', name: '櫻桃', category: 'fruit', waterPct: 84, sugarPct: 10, otherSolidsPct: 6, totalSolidsPct: 16, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-fig', name: '無花果', category: 'fruit', waterPct: 85, sugarPct: 8, otherSolidsPct: 7, totalSolidsPct: 15, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-apple', name: '蘋果', category: 'fruit', waterPct: 81, sugarPct: 13, otherSolidsPct: 6, totalSolidsPct: 19, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-grape', name: '葡萄', category: 'fruit', waterPct: 81, sugarPct: 14, otherSolidsPct: 5, totalSolidsPct: 19, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-guava', name: '芭樂', category: 'fruit', waterPct: 78, sugarPct: 7, otherSolidsPct: 15, totalSolidsPct: 22, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-dragonfruit', name: '火龍果', category: 'fruit', waterPct: 74, sugarPct: 11, otherSolidsPct: 15, totalSolidsPct: 26, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-glucose-powder', name: '葡萄糖粉', category: 'other_sugar', waterPct: 19, sugarPct: 81, otherSolidsPct: 0, totalSolidsPct: 81, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-dextrose-powder', name: '右旋糖粉', category: 'other_sugar', waterPct: 5, sugarPct: 95, otherSolidsPct: 0, totalSolidsPct: 95, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-trehalose', name: '海藻糖', category: 'other_sugar', waterPct: 10, sugarPct: 90, otherSolidsPct: 0, totalSolidsPct: 90, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: 0.45, pacCoefficient: 0.45 },
  { id: 'demo-invert-sugar', name: '轉化糖', category: 'other_sugar', waterPct: 25, sugarPct: 75, otherSolidsPct: 0, totalSolidsPct: 75, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
  { id: 'demo-maltodextrin', name: '麥芽糊精', category: 'other_sugar', waterPct: 4, sugarPct: 96, otherSolidsPct: 0, totalSolidsPct: 96, recommendedMinPct: null, recommendedMaxPct: null, podCoefficient: null, pacCoefficient: null },
]
